### ISSUE TITLE
Why not directly generate training data for the generator using GPT4?

### ISSUE THREAD

**Issue by kakaxisisan** [AkariAsai/self-rag#6] opened 2023-10-26 06:03 UTC

**Comment by AkariAsai** [comment] 2023-10-26 18:02
We briefly discussed in Section 3.2.1 in our paper, and there are essentially two reasons:
1. We have four different types of reflection tokens and insert them almost at the segment level, resulting in a million orders of inferences if we run GPT-4 to insert reflection tokens at each segment independently. This is simply too expensive for us to afford, especially since our model input can get long (i.e., OpenAI API costs depend on input context length). 
2. We are also afraid that relying on GPT-4 completely to insert special tokens may also hurt reproducibility in the future, as the model behaviors have been reported to change over time e.g., [How is ChatGPT's behavior changing over time? (Chen et al., 2023])(https://arxiv.org/abs/2307.09009).

**Comment by AkariAsai** [comment] 2023-10-28 22:43
I am closing this issue for now but feel free to reopen it!

**Closed by AkariAsai** 2023-10-28 22:43 UTC
